# Generated by Django 4.2.4 on 2023-10-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_edad_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='salario_empleado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
