# Generated by Django 4.2.4 on 2023-10-01 19:33

from django.db import migrations, models
import empleados.models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_salario_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto_empleado',
            field=models.ImageField(blank=True, null=True, upload_to=empleados.models.custom_upload_to),
        ),
    ]
